#/bin/bash

WWW=/usr/lib/cgi-bin/

all:
	cp spec/test/project3_testdata/t[1-5].txt $(WWW)
	cp spec/cgi/hello.cgi $(WWW)
	cp spec/cgi/printenv.cgi $(WWW)
	cp spec/cgi/welcome.cgi $(WWW)
	cp spec/resource/form_get.htm $(WWW)


#clean:
